/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package zahranform080525;

/**
 *
 * @author Suga
 */
public class Form extends javax.swing.JFrame {

    /**
     * Creates new form Form
     */
    public Form() {
        initComponents();
        clearScreen();
    }
    
    public void clearScreen(){
        txtNama.setText("");
        txtAlamat.setText("");
        txtUmur.setText("");
        txtMatematika.setText("");
        txtIndo.setText("");
        txtIlmuP.setText("");
        txtAverage.setText("");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        txtIlmuP = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAlamat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtUmur = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtMatematika = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtIndo = new javax.swing.JTextField();
        Hitung = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtAverage = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel3.setText("Ilm.Pengetahuan");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 230, 90, 20);

        txtIlmuP.setText("jTextField2");
        txtIlmuP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIlmuPActionPerformed(evt);
            }
        });
        getContentPane().add(txtIlmuP);
        txtIlmuP.setBounds(120, 230, 250, 22);

        jLabel4.setText("Nama");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 30, 40, 20);

        txtNama.setText("jTextField2");
        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });
        getContentPane().add(txtNama);
        txtNama.setBounds(90, 30, 280, 22);

        jLabel5.setText("Alamat");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 70, 40, 20);

        txtAlamat.setText("jTextField2");
        txtAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlamatActionPerformed(evt);
            }
        });
        getContentPane().add(txtAlamat);
        txtAlamat.setBounds(90, 70, 280, 22);

        jLabel6.setText("Umur");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 110, 40, 20);

        txtUmur.setText("jTextField2");
        txtUmur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUmurActionPerformed(evt);
            }
        });
        getContentPane().add(txtUmur);
        txtUmur.setBounds(90, 110, 280, 22);

        jLabel7.setText("Matematika");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 150, 70, 20);

        txtMatematika.setText("jTextField2");
        txtMatematika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatematikaActionPerformed(evt);
            }
        });
        getContentPane().add(txtMatematika);
        txtMatematika.setBounds(120, 150, 250, 22);

        jLabel8.setText("Bhs. Indo");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 190, 60, 20);

        txtIndo.setText("jTextField2");
        txtIndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIndoActionPerformed(evt);
            }
        });
        getContentPane().add(txtIndo);
        txtIndo.setBounds(120, 190, 250, 22);

        Hitung.setText("Hitung");
        Hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitungActionPerformed(evt);
            }
        });
        getContentPane().add(Hitung);
        Hitung.setBounds(25, 280, 340, 23);

        jLabel1.setText("Rata-rata");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 330, 60, 20);

        txtAverage.setText("jTextField1");
        getContentPane().add(txtAverage);
        txtAverage.setBounds(120, 330, 250, 22);

        setBounds(0, 0, 441, 428);
    }// </editor-fold>//GEN-END:initComponents

    private void txtIlmuPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIlmuPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIlmuPActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void txtAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlamatActionPerformed

    private void txtUmurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUmurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUmurActionPerformed

    private void txtMatematikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatematikaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatematikaActionPerformed

    private void txtIndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIndoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIndoActionPerformed

    private void HitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungActionPerformed
        // TODO add your handling code here:
        StudentRecord student = new StudentRecord();
        student.setName(txtNama.getText());
        student.setAddress(txtAlamat.getText());
        student.setAge(Integer.parseInt(txtUmur.getText()));
        student.setMathGrade(Double.parseDouble(txtMatematika.getText()));
        student.setIndoGrade(Double.parseDouble(txtIndo.getText()));
        student.setScienceGrade(Double.parseDouble(txtIlmuP.getText()));
        txtAverage.setText(String.valueOf(student.getAverage()));
    }//GEN-LAST:event_HitungActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Hitung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtAverage;
    private javax.swing.JTextField txtIlmuP;
    private javax.swing.JTextField txtIndo;
    private javax.swing.JTextField txtMatematika;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtUmur;
    // End of variables declaration//GEN-END:variables
}
